# Generated by Django 4.1.7 on 2023-03-10 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_remove_libro_description_libro_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='image',
            new_name='imagen',
        ),
    ]
